version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    volumes:
    - .:/app
      - /app/node_modules
      
  tests:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      target: dev
    volumes:
    - .:/app
      - /app/node_modules
    command: ['npm', 'run', 'test']
